galaxy_info:
  role_name: vector
  namespace: edwardburlakov
  author: Edward Burlakov
  description: Role for installation of Vector role
  company: Unix Ltd.
  license: MIT
  min_ansible_version: "2.8"
  platforms:
    - name: centos
      versions:
        - 7
        - 8
  galaxy_tags:
    - lighthouse
    - clickhouse
    - nginx
    - logs