---
- name: Create file with new content.
  hosts: lesson
  tasks:
    - name: Fill content
      become: true
      my_own_module:
        path: "/root/"
        content: "Hello, Edward I!"
        name: "first.md"

