---
- name: Running of my own module
  hosts: localhost
  tasks:
    - name: Execute it
      become: true
      edwardburlakov.my_own_collection.my_own_module:
         path: "{{ fpath }}"
         content: "{{ fcontent }}"
         name: "{{ fname }}"