---
<<<<<<< HEAD
- name: "Print os fact"
=======
  - name: "Print os fact"
>>>>>>> 0a6a69c14ab1bb64dca08ec198a418f11cec33aa
    hosts: all
    gather_facts: true
    tasks:
      - name: "Print OS"
        ansible.builtin.debug:
          msg: "{{ ansible_distribution }}"
      - name: Print fact
        ansible.builtin.debug:
          msg: "{{ some_fact }}"
