---
  - name: Assert lighthouse role
    hosts: lighthouse
    roles:
      - lighthouse-role
  - name: Assert vector role
    hosts: vector
    roles:
      - vector-role
  - name: Assert clickhouse role
    hosts: clickhouse
    roles:
      - ansible-clickhouse
