---
  - name: Assert lighthouse role
    hosts: lighthouse
    roles:
      - ansible-lighthouse-role
  - name: Assert vector role
    hosts: vector
    roles:
      - ansible-vector-role
  - name: Assert clickhouse role
    hosts: clickhouse
    roles:
      - ansible-clickhouse-role
