---
- name: Prepare all hosts
  hosts: all
  tasks:
    - name: Create group
      become: true
      ansible.builtin.group:
        name: "{{ user_group }}"
        state: present
    - name: Create user
      become: true
      ansible.builtin.user:
        name: "{{ user_name }}"
        generate_ssh_key: true
      register: ssh_key_info
    - name: Install JDK
      become: true
      ansible.builtin.package:
        name: "{{ java_packages }}"
        state: present
