---
  nginx:
    hosts:
      nginx-01:
        ansible_host: 51.250.110.236
        ansible_connection: ssh
        ansible_user: bes
  lighthouse:
    hosts:
      lighthouse-01:
        ansible_host: 51.250.110.236
        ansible_connection: ssh
        ansible_user: bes
  clickhouse:
    hosts:
      clickhouse-01:
        ansible_host: 51.250.23.140
        ansible_connection: ssh
        ansible_user: bes
  vector:
    hosts:
      vector-01:
        ansible_host: 51.250.17.182
        ansible_connection: ssh
        ansible_user: bes

