---
clickhouse-hosts:
    hosts:
        clickhouse-01:
            ansible_host: localhost
            ansible_connection: local
#           ansible_user: root
#           ansible_password: centos22
vector-hosts:
    hosts:
        vector-01:
            ansible_host: 88.11.2
            ansible_connection:
           ansible_user: root
           ansible_password: centos22
#
#  lighthouse-hosts:
#    hosts:
#       lighthouse-01:
#           ansible_host: 88.11.22.22
#           ansible_connection: ssh
#           ansible_user: root
#           ansible_password: centos22
#  nginx-hosts:
#    hosts:
#      clickhouse-01:
#           ansible_host: 88.11.22.11
#           ansible_connection: ssh
#           ansible_user: root
#           ansible_password: centos22
#      lighthouse-01:
#           ansible_host: 88.11.22.22
#           ansible_connection: ssh
#           ansible_user: root
#           ansible_password: centos22
#      vector-01:
#           ansible_host: 88.11.22.33
#           ansible_connection: ssh
#           ansible_user: root
#           ansible_password: centos22
